### ISSUE TITLE
Skill tree

### ISSUE THREAD

**Issue by mklabs** [mklabs/twmods#16]
- [x] Work out the few unique remaining skills
- [x] Remove Ghorros one, rename skill, add correct loc
- [x] Duplicate Kholek skill, rework loc.
- [x] work on loc.
- [x] brass armour anciliary char skill (#15)

**Comment by mklabs** [comment]
This issue was moved to mklabs/taurox-beastmen-mod#23
